"""empty message

Revision ID: 6ba23b1ccf69
Revises: 6804698a91ed
Create Date: 2025-03-12 04:16:15.109437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba23b1ccf69'
down_revision = '6804698a91ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
